name: Auto-merge Dependabot PRs

on:
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event.check_suite.conclusion == 'success'
    steps:
      - name: Merge Dependabot PRs
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const ref   = context.payload.check_suite.head_sha;
            const prs   = context.payload.check_suite.pull_requests || [];

            for (const refPR of prs) {
              // 1) Fetch full PR data
              const { data: pr } = await github.rest.pulls.get({
                owner, repo, pull_number: refPR.number
              });

              // 2) Only Dependabot-authored PRs
              if (pr.user?.login !== 'dependabot[bot]') continue;

              // 3a) Check combined status state
              const { data: combined } = await github.rest.repos.getCombinedStatusForRef({
                owner, repo, ref: pr.head.sha
              });
              if (combined.state !== 'success') continue;

              // 3b) Check every Check Run
              const { data: runs } = await github.rest.checks.listForRef({
                owner, repo, ref: pr.head.sha
              });
              if (runs.check_runs.some(r => r.conclusion !== 'success')) continue;

              // 4) All green → squash-merge
              await github.rest.pulls.merge({
                owner,
                rep
